### ISSUE TITLE
Travis: Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by szepeviktor** [svenkreiss/html5validator#18]
Hello!

html5validator was working but now
```
WARNING:html5validator.validator:Exception in thread "main" java.lang.UnsupportedClassVersionError: nu/validator/client/SimpleCommandLineValidator : Unsupported major.minor version 52.0

	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
```
Build log: https://travis-ci.org/szepeviktor/ip-info/builds/126924244#L140

Travis config: https://github.com/szepeviktor/ip-info/blob/gh-pages/.travis.yml

**Comment by szepeviktor** [comment]
Could it be Java 1.7 <-> 1.8 problem?

**Comment by szepeviktor** [comment]
Maybe?
> Since version 0.2, Java 8 is required.

**Comment by szepeviktor** [comment]
Yes, on Java 8 there's no problem.

**Comment by remram44** [comment]
I think it would be better if this was compatible with Java 7. In particular because this is what is available on Travis.

With the recent updates, I need `sudo: required` and I need to apt-update and install Java 8, which makes builds run much slower. Are Java 8 features absolutely required?
